baby_emotion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("emotions.urls")),
    path('', include("user_creation.urls"))
]

emotions/urls.py
from django.urls import path
from emotions import views

app_name = 'emotions'
urlpatterns = [
    path('', views.predict_emotion, name='predict_emotion'),
    path('', views.home, name ="home"),

]

user_creation/urls.py
from django.urls import path
from user_creation import views


app_name = 'user_creation'

urlpatterns = [
    # Authentication URLs
    path('login/', views.login_user, name ='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
]

emotions/models.py
from django.db import models

# Create your models here.

user_creation/models.py
from django.db import models

# Create your models here.

user_creation/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class EditProfileForm(UserChangeForm):
    password = forms.CharField(label="", widget=forms.TextInput(attrs={'type': 'hidden'}))

    class Meta:
        model = User
        # excludes private information from User
        fields = ('username', 'first_name', 'last_name', 'email', 'password',)


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="",
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}), )
    first_name = forms.CharField(label="", max_length=100,
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label="", max_length=100,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields[
            'username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields[
            'password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields[
            'password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

emotions/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

import tensorflow as tf
import tensorflow_io as tfio
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import base64

# Load the TensorFlow model
reloaded_model = tf.saved_model.load('model')


# my_classes = ['Discomfort', 'Burping', 'Tired', 'Belly_pain', 'Hungry']


@tf.function
def load_wav_16k_mono(file_contents):
    """ read in a waveform file and convert to 16 kHz mono """
    wav, sample_rate = tf.audio.decode_wav(
        file_contents.read(),
        desired_channels=1)
    wav = tf.squeeze(wav, axis=-1)
    sample_rate = tf.cast(sample_rate, dtype=tf.int64)
    wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
    return wav


@login_required(login_url='user_creation:login')
def predict_emotion(request):
    # Handle audio input from the request
    if request.method == 'POST':
        audio_data = request.FILES.get('audio')

        # Preprocess and extract relevant features from the audio data
        if audio_data:
            reloaded_results = reloaded_model(load_wav_16k_mono(audio_data))

            my_classes = ['Discomfort', 'Burping', 'Tired', 'Belly_pain', 'Hungry']
            result = my_classes[tf.argmax(reloaded_results)]
            probs = tf.nn.softmax(reloaded_results) * 100
            probs = tf.nn.softmax(reloaded_results)
            plt.bar(my_classes, probs)
            plt.savefig('graph.png')
            plt.clf()

            # Encode the image data as base64
            with open('graph.png', 'rb') as img_file:
                image_data = img_file.read()
                image_base64 = base64.b64encode(image_data).decode('utf-8')

            context = {
                'predicted_emotion': result,
                'emotion_graph': image_base64
            }

            return render(request, 'index.html', context)
        else:
            # Audio file is not uploaded
            error_message = 'Please upload an audio sample.'
            context = {
                'error_message': error_message,
            }
            return render(request, 'index.html', context)

    # Return the predicted emotion as a response
    return render(request, 'index.html')


def home(request):
    return render(request, 'index.html', {})

user_creation/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from .forms import SignUpForm, EditProfileForm


# Create your views here.
def login_user(request):
    if request.method == 'POST':  # if someone fills out form , Post it
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:  # if user exist
            login(request, user)
            messages.success(request, ('Youre logged in'))
            return redirect('emotions:home')  # routes to 'home' on successful login
        else:
            messages.success(request, ('Error logging in'))
            return redirect('user_creation:login')  # re routes to login page upon unsucessful login
    else:
        return render(request, 'user_creation/login.html', {})


def logout_user(request):
    logout(request)
    messages.success(request, ('Youre now logged out'))
    return redirect('emotions:home')


def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ('Youre now registered'))
            return redirect('emotions:home')
    else:
        form = SignUpForm()

    context = {'form': form}
    return render(request, 'user_creation/register.html', context)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, ('You have edited your profile'))
            return redirect('emotions:home')
    else:  # passes in user information
        form = EditProfileForm(instance=request.user)

    context = {'form': form}
    return render(request, 'user_creation/edit_profile.html', context)


# return render(request, 'authenticate/edit_profile.html',{})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, ('You have edited your password'))
            return redirect('emotions:home')
    else:  # passes in user information
        form = PasswordChangeForm(user=request.user)

    context = {'form': form}
    return render(request, 'user_creation/change_password.html', context)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Group-4</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'emotions:home' %}">BABY TRANSLATOR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">

            {# Will know if user is logged in or not#}
            {% if user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user_creation:logout' %}">Logout</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user_creation:edit_profile' %}">Edit Profile</a>
                </li>



            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user_creation:login' %}">Login</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user_creation:register' %}">Register</a>
                </li>

            {% endif %}

        </ul>

    </div>
</nav>
<br/>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger alart-dismissable" role="alert">
                <button class="close" data-dismiss="alert">
                    <small><sup>x</sup></small>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}


    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="color:royalblue">Upload a file</h1>
    <form method="POST" enctype="multipart/form-data" action="{% url 'emotions:predict_emotion' %}">
        {% csrf_token %}
        <input type="file" name="audio" accept=".wav">
        <input class="btn btn-primary" type="submit" value="Predict">
    </form>
    <br>
    {% if predicted_emotion %}
        <h2>Predicted Emotion: <span style="color:forestgreen ">{{ predicted_emotion }}</span></h2>
        {% if emotion_graph %}
            <img src="data:image/png;base64,{{ emotion_graph }}" alt="Emotion Graph">
        {% endif %}
    {% endif %}
    {% if error_message %}
        <p style="color:red">{{ error_message }}</p>
    {% endif %}
{% endblock %}

templates/user_creation/change_password.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="text-center"> Change Password </h2>


    <form method="POST" action="{% url 'user_creation:change_password' %}">
        {% csrf_token %}

        {% if form.errors %}

            <div class="alert alert-danger alart-dismissable" role="alert">
                <button class="close" data-dismiss="alert">
                    <small><sup>x</sup></small>
                </button>


                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}

                {% endfor %}


            </div>

        {% endif %}


        {{ form.as_p }}

        {# button #}
        <input type="submit" value="Change Password" class=" btn btn-secondary">
    </form>

{% endblock %}

templates/user_creation/edit_profile.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="text-center"> Edit Profile </h2>


    <form method="POST" action="{% url 'user_creation:edit_profile' %}">
        {% csrf_token %}

        {% if form.errors %}

            <div class="alert alert-danger alart-dismissable" role="alert">
                <button class="close" data-dismiss="alert">
                    <small><sup>x</sup></small>
                </button>


                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}

                {% endfor %}


            </div>

        {% endif %}


        {{ form.as_p }}


        <input type="submit" value="Edit Profile" class=" btn btn-secondary">
        <p><small><a href="{% url 'user_creation:change_password' %}">Click here</a> to change your password</small></p>
    </form>

{% endblock %}

templates/user_creation/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <style>
        .divider:after,
        .divider:before {
            content: "";
            flex: 1;
            height: 1px;
            background: #eee;
        }

        .h-custom {
            height: calc(100% - 73px);
        }

        @media (max-width: 450px) {
            .h-custom {
                height: 100%;
            }
        }
    </style>

    <section class="vh-100">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="{% static 'Technische_Hochschule_Deggendorf_logo.jpg' %}"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
                            <p class="lead fw-normal mb-0 me-3">Sign in</p>
                            <button type="button" class="btn btn-primary btn-floating mx-1">
                                <i class="fab fa-facebook-f"></i>
                            </button>

                            <button type="button" class="btn btn-primary btn-floating mx-1">
                                <i class="fab fa-twitter"></i>
                            </button>

                            <button type="button" class="btn btn-primary btn-floating mx-1">
                                <i class="fab fa-linkedin-in"></i>
                            </button>
                        </div>

                        <div class="divider d-flex align-items-center my-4">
                            <p class="text-center fw-bold mx-3 mb-0">Baby Emotion AI-Predictor</p>
                        </div>

                        <div class="form-outline mb-4">
                            <!--suppress HtmlFormInputWithoutLabel -->
                            <input type="text" id="id_username" class="form-control form-control-lg"
                                   placeholder="Enter Username" name="username">
                        </div>

                        <div class="form-outline mb-3">
                            <!--suppress HtmlFormInputWithoutLabel -->
                            <input type="password" id="id_password" class="form-control form-control-lg"
                                   placeholder="Enter Password" name="password">
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3"/>
                                <label class="form-check-label" for="form2Example3">
                                    Remember me
                                </label>
                            </div>
                            <a href="{% url 'user_creation:change_password' %}" class="text-body">Forgot password?</a>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login
                            </button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a
                                    href="{% url 'user_creation:register' %}"
                                    class=" link-danger">Register</a>
                            </p>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
            <div class="text-white mb-3 mb-md-0">
                Copyright © 2020. All rights reserved.
            </div>
            <!-- Right -->
            <div>
                <a href="#!" class="text-white me-4">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="#!" class="text-white me-4">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#!" class="text-white me-4">
                    <i class="fab fa-google"></i>
                </a>
                <a href="#!" class="text-white">
                    <i class="fab fa-linkedin-in"></i>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

templates/user_creation/register.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="text-center"> Register </h2>

    <div class="col-md-6 offset-md-3">

        <form method="POST" action="{% url 'user_creation:register' %}">
            {% csrf_token %}

            {% if form.errors %}
                <div class="alert alert-danger alart-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small><sup>x</sup></small>
                    </button>


                    {% for field in form %}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}

                    {% endfor %}


                </div>



            {% endif %}


            {{ form.as_p }}


            <input type="submit" value="Register" class=" btn btn-secondary">
        </form>
    </div>
{% endblock %}